base/urls.py
from django.urls import path

from base.views import (
    deactivate_account_view,
    delete_account_view,
    email_verify_view,
    home_view,
    login_view,
    logout_view,
    password_change_view,
    password_reset_request_view,
    password_reset_view,
    profile_view,
    register_view,
    search_account_view,
    update_view,
)

app_name = "base"

urlpatterns = [
    path("", home_view, name="home"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_view, name="register"),
    path("profile/", profile_view, name="profile"),
    path("profile/<str:user_id>", profile_view, name="profile"),
    path("account_update/", update_view, name="update-profile"),
    path("account_search/", search_account_view, name="search-profile"),
    path("email_verification/<uidb64>/<token>/", email_verify_view, name="email-verify"),
    path("password_change/", password_change_view, name="password-change"),
    path("password_reset_request/", password_reset_request_view, name="password-reset-request"),
    path("password_reset/<uidb64>/<token>/", password_reset_view, name="password-reset"),
    path("user_deactivate/", deactivate_account_view, name="account-deactivate"),
    path("user_delete/", delete_account_view, name="account-delete"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls", namespace="base")),
    path("mcq/", include("mcqapp.urls", namespace="mcqapp")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "base.views.page_not_found_view"

base/forms.py
from django import forms
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from base.models import User
from base.widgets import CustomFileInput


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=255, widget=forms.EmailInput)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data["email"]
        return email.lower()

    def is_valid(self):
        super().is_valid()
        email = self.cleaned_data["email"]
        password = self.cleaned_data["password"]
        user = authenticate(email=email, password=password)
        if user:
            return True
        return False


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=127)

    class Meta:
        model = User
        fields = ("avatar", "email", "name", "usertype", "password1", "password2")


class UserUpdateForm(forms.ModelForm):
    avatar = forms.FileField(widget=CustomFileInput)

    class Meta:
        model = User
        fields = ("avatar", "email", "name", "usertype")


class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "autofocus": True}),
    )
    new_password1 = forms.CharField(
        label=_("New password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError("Incorrect current password.")
        return old_password

    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError("The two passwords didnt match.")
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(max_length=127)

    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None
        if not user:
            raise forms.ValidationError("Email not registered in our database.")


class PasswordResetForm(forms.Form):
    password1 = forms.CharField(
        label=_("New password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )
    password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError("The two passwords didnt match.")
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

base/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from base.forms import (
    LoginForm,
    PasswordChangeForm,
    PasswordResetForm,
    PasswordResetRequestForm,
    RegistrationForm,
    UserUpdateForm,
)
from base.models import Token, User
from base.tokens import account_activation_token, password_reset_token
from project.tasks import send_password_reset_email, send_user_activation_email


def get_login_type(user):
    try:
        return user.usertype.name
    except Exception as e:
        return ""


def check_token_is_valid(token, user):
    try:
        token_instance = Token.objects.filter(token=token).first()
        if not token_instance.is_expired and token_instance.user == user:
            return True
        else:
            return False
    except Token.DoesNotExist:
        return False


def home_view(request, *args, **kwargs):
    return render(request, "base/home_page.html")


def register_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if user.is_authenticated:
        messages.info(request, "You are already registered.")
        return redirect("base:home")

    form = RegistrationForm(request.POST or None, request.FILES or None)

    if request.method == "POST":
        if form.is_valid():
            user = form.save()

            site = get_current_site(request)
            domain = site.domain
            if settings.CELERY_SERVER_RUNNING:
                send_user_activation_email.delay(user.id, domain)
            else:
                send_user_activation_email(user.id, domain)
            messages.success(
                request,
                f"An email with verification link is sent to your Email ID. Verify Your account before login.",
            )

            return redirect("base:login")

        else:
            messages.error(request, f"Error in data validation.")

    context["form"] = form
    return render(request, "base/register_page.html", context)


def login_view(request, *args, **kwargs):
    context = {}

    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(request, email=email, password=password)

            if not user.is_active:
                user.is_active = True

            if not user.is_email_verified:
                site = get_current_site(request)
                domain = site.domain
                if settings.CELERY_SERVER_RUNNING:
                    send_user_activation_email.delay(user.id, domain)
                else:
                    send_user_activation_email(user.id, domain)
                messages.success(
                    request,
                    f"An email with verification link is sent to your Email ID. Verify Your account before login.",
                )
                return redirect("base:home")

            login(request, user)
            messages.success(request, "Login Successfull.")
            redirect_url = request.POST.get("next", None)
            if redirect_url:
                return redirect(redirect_url)

            login_type = get_login_type(user)
            match login_type:
                case "administrator":
                    pass
                case other:
                    return redirect("base:home")

        else:
            messages.error(request, f"Invalid email or password.")

    context["form"] = form
    return render(request, "base/login_page.html", context)


def logout_view(request, *args, **kwargs):
    logout(request)
    messages.success(request, "Logged out successfully.")
    return redirect("base:login")


@login_required
def profile_view(request, *args, **kwargs):
    context = {}

    user_id = kwargs.get("user_id", None)
    if user_id:
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            raise Http404("User not found.")
    else:
        user = request.user

    context["user"] = user
    return render(request, "base/profile_page.html", context)


@login_required
def update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if request.method == "GET":
        form = UserUpdateForm(instance=user)

    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("base:profile")
        else:
            messages.error(request, f"Error...")

    context["form"] = form
    return render(request, "base/profile_update_page.html", context)


@login_required
def deactivate_account_view(request, *args, **kwargs):
    user = request.user

    if request.method == "POST":
        user.is_active = False
        logout(request)
        messages.success(request, f"Your account has been deactivated. Login anytime to reactivate it.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("base:home")


@login_required
def delete_account_view(request, *args, **kwargs):
    user = request.user

    if request.method == "POST":
        user.delete()
        messages.success(request, f"Your account has been deleted successfully.")
    else:
        messages.error(request, "Something went wrong.")
    return redirect("base:home")


@login_required
def search_account_view(request, *args, **kwargs):
    context = {}

    if request.method == "GET":
        text = request.GET.get("user_query")
        if text == "":
            messages.info(request, "Please enter some text in search box.")
            return redirect("base:home")

        users = User.objects.filter(Q(email__icontains=text) | Q(name__icontains=text)).exclude(id=request.user.id)
        context["users"] = users

    return render(request, "base/search_user_page.html", context)


def email_verify_view(request, uidb64, token, *args, **kwargs):
    try:
        user_id = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=user_id)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    token_valid = check_token_is_valid(token=token, user=user)
    if not token_valid:
        messages.error(
            request,
            "Either the link is invalid or it is expired. Please proceed to login page and try logging in to get new link.",
        )
        return redirect("base:home")

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.is_email_verified = True
        user.save()
        login(request, user)
        messages.success(request, f"An account for {user.name} created successfully.")
        return redirect("base:home")
    else:
        messages.error(request, f"Something went wrong.")
        return redirect("base:home")


@login_required
def password_change_view(request, *args, **kwargs):
    context = {}

    user = request.user
    form = PasswordChangeForm(user, request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"Password changed successfully. Please login with new password to continue.",
            )
        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["header"] = "Change Password"
    context["button_text"] = "Change"
    return render(request, "base/password/password_form.html", context)


def password_reset_request_view(request, *args, **kwargs):
    context = {}

    form = PasswordResetRequestForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            email = request.POST["email"]

            site = get_current_site(request)
            domain = site.domain
            if settings.CELERY_SERVER_RUNNING:
                send_password_reset_email.delay(email, domain)
            else:
                send_password_reset_email(email, domain)
            messages.success(
                request,
                f"An email with password reset link is sent to your Email ID. Verify Your account before login.",
            )

        else:
            form = form
            messages.error(request, "Error.")

    context["form"] = form
    context["header"] = "Request Password Reset"
    context["button_text"] = "Request"
    return render(request, "base/password/password_form.html", context)


def password_reset_view(request, uidb64, token, *args, **kwargs):
    try:
        user_id = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=user_id)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    context = {}

    token_valid = check_token_is_valid(token=token, user=user)
    if not token_valid:
        messages.error(
            request,
            "Either the link is invalid or it is expired. Please request password reset again.",
        )
        return redirect("base:home")

    if user is not None and account_activation_token.check_token(user, token):
        form = PasswordResetForm(user, request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                messages.success(
                    request,
                    f"Your password has been reset. Please login to continue.",
                )
                return redirect("base:login")
            else:

base/templates/base/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block html %}

{% include 'base/snippets/header.html' %}
{% include 'base/snippets/message.html' %}

{% block body %}{% endblock body %}

{% endblock html %}

base/templates/base/home_page.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block body %} 
<div class="flex justify-center items-center pt-4">Home</div>
{% endblock body %}

base/templates/base/login_page.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load tailwind_filters %}

{% load account socialaccount %}
{% get_providers as socialaccount_providers %}

{% block title %}Login{% endblock title %}

{% block body %}
<div class="flex flex-col items-center justify-center mt-4 mb-2 mx-8">
    <form class="w-full md:w-1/2 lg:w-1/3 pb-2" method="post" enctype="multipart/form-data">
        <legend class="text-3xl font-bold border-b border-gray-500 pb-1 mb-2">Login User</legend>
        {% csrf_token %}
        {{form|crispy}}
        <div class="flex items-end justify-between mt-2 pt-2 pb-2 border-t border-gray-500">
            <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-3 rounded" type="submit">Login</button>
            <a href="{% url 'base:password-reset-request' %}" class="text-blue-700 mx-1 cursor-pointer">Forgot Password</a>
        </div>
        <div class="flex items-center pt-1 border-t border-gray-500">
            <span class="">Need an account?</span>
            <a href="{% url 'base:register' %}" class="text-blue-700 mx-1 cursor-pointer">Register</a>
        </div>
    </form>
    <h2 class="my-2">OR</h2>
    <a class="mt-2 px-3 py-2 bg-blue-500 hover:bg-blue-700 text-white rounded" href="{% provider_login_url 'google' %}">Login with Google</a>
</div>
{% endblock body %}

base/templates/base/page_not_found.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Page Not Found</title>
</head>
<body>
    <div class="flex justify-center items-center mt-4">
       <h1 class="mt-4">Page Not Found</h1>
    </div>
</body>
</html>

base/templates/base/profile_page.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block body %}
<div class="flex justify-center items-center pt-4">
    <div class="flex flex-col shadow-md mx-8 px-2 py-2 md:px-4 md:py-4 rounded-md">
        <div class="flex flex-col md:flex-row">
            <div class="flex items-center justify-center mx-2 my-2 rounded-sm">
                <img class="w-80 h-80 rounded-md" src="{{ user.avatar.url }}" alt="profile pic">
            </div>
            <div class="flex flex-col items-center mx-4 my-4 px-4 py-4">
                <h5 class="text-xl">{{ user.email }}</h5>
                <h5 class="text-lg">{{ user.name }}</h5>
            </div>
        </div>
        {% if user.id == request.user.id %}
        <div class="flex items-center justify-center flex-wrap border-t border-gray-500 pt-2">
            <a class="my-2 px-3 py-2 mx-2 bg-blue-500 hover:bg-blue-700 text-white rounded" href="{% url 'base:update-profile' %}">Update Profile</a>
            <button id="id_deactivate_account_button" class="mx-2 px-3 py-2 bg-red-500 hover:bg-red-700 text-white rounded">Deactivate Account</button>
            <button id="id_delete_account_button" class="mx-2 px-3 py-2 bg-red-500 hover:bg-red-700 text-white rounded">Delete Account</button>
        </div>
        {% endif %}
    </div>
</div>

<!-- Deactivate Account Modal -->
<div id="id_deactivate_account_modal" class="modal h-screen w-full fixed left-0 top-0 flex justify-center bg-black bg-opacity-50 hidden">
    <div class="px-4 py-2 bg-white rounded shadow-lg w-1/3 h-fit">
        <div class="px-4 py-2 border-b ">
            <h3 class="text-2xl font-bold text-red-700">Deactivate Account</h3>
        </div>
        <div class="my-2 px-4 pt-2 pb-4 border-b">
            Are you sure you want to deactivate your account?
        </div>
        <div class="flex justify-end my-2 px-4 py-2">
            <button id="id_deactivate_modal_cancel" class="mx-2 px-3 py-2 bg-gray-500 hover:bg-gray-700 text-white rounded">Cancel</button>
            <form method="post" action="{% url 'base:account-deactivate' %}">
                {% csrf_token %}
                <button class="mx-2 px-3 py-2 bg-red-500 hover:bg-red-700 text-white rounded" type="submit">Deactivate</button>
            </form>
        </div>
    </div>
</div>

<!-- Delete Account Modal -->
<div id="id_delete_account_modal" class="modal h-screen w-full fixed left-0 top-0 flex justify-center bg-black bg-opacity-50 hidden">
    <div class="px-4 py-2 bg-white rounded shadow-lg w-1/3 h-fit">
        <div class="px-4 py-2 border-b ">
            <h3 class="text-2xl font-bold text-red-700">Delete Account</h3>
        </div>
        <div class="my-2 px-4 pt-2 pb-4 border-b">
            Are you sure you want to delete your account?
        </div>
        <div class="flex justify-end my-2 px-4 py-2">
            <button id="id_delete_modal_cancel" class="mx-2 px-3 py-2 bg-gray-500 hover:bg-gray-700 text-white rounded">Cancel</button>
            <form method="post" action="{% url 'base:account-delete' %}">
                {% csrf_token %}
                <button class="mx-2 px-3 py-2 bg-red-500 hover:bg-red-700 text-white rounded" type="submit">Delete</button>
            </form>
        </div>
    </div>
</div>

<script>
    function showDeactivateAccountModal() {
        let modal = document.getElementById("id_deactivate_account_modal")
        modal.classList.remove("hidden")
    }

    function hideDeactivateAccountModal() {
        let modal = document.getElementById("id_deactivate_account_modal")
        modal.classList.add("hidden")
    }

    function showDeleteAccountModal() {
        let modal = document.getElementById("id_delete_account_modal")
        modal.classList.remove("hidden")
    }

    function hideDeleteAccountModal() {
        let modal = document.getElementById("id_delete_account_modal")
        modal.classList.add("hidden")
    }

    document.getElementById("id_deactivate_account_button").addEventListener("click", showDeactivateAccountModal)
    document.getElementById("id_deactivate_modal_cancel").addEventListener("click", hideDeactivateAccountModal)
    document.getElementById("id_delete_account_button").addEventListener("click", showDeleteAccountModal)
    document.getElementById("id_delete_modal_cancel").addEventListener("click", hideDeleteAccountModal)
</script>
{% endblock body %}

base/templates/base/profile_update_page.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load tailwind_filters %}

{% block title %}Update Profile{% endblock title %}

{% block body %}
<div class="flex items-center justify-center mt-4 mb-2 mx-8">
    <form class="w-full md:w-1/2 lg:w-1/3 pb-2" method="post" enctype="multipart/form-data">
        <legend class="text-3xl font-bold border-b border-gray-500 pb-1 mb-2">Update Profile</legend>
        {% csrf_token %}
        {{form|crispy}}
        <div class="flex items-end justify-between mt-2 pt-2 pb-2 border-t border-gray-500">
            <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-3 rounded" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock body %}

base/templates/base/register_page.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load tailwind_filters %}

{% block title %}Register{% endblock title %}

{% block body %}
<div class="flex items-center justify-center mt-4 mb-2 mx-8">
    <form class="w-full md:w-1/2 lg:w-1/3 pb-2" method="post" enctype="multipart/form-data">
        <legend class="text-3xl font-bold border-b border-gray-500 pb-1 mb-2">Register User</legend>
        {% csrf_token %}
        {{form|crispy}}
        <div class="flex items-end justify-between mt-2 pt-2 border-t border-gray-500">
            <button class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-3 rounded" type="submit">Register</button>
            <div class="flex items-center">
                <span class="">Already have an account?</span>
                <a href="{% url 'base:login' %}" class="text-blue-700 mx-1 cursor-pointer">Login</a>
            </div>
        </div>
    </form>
</div>
{% endblock body %}

base/templates/base/search_user_page.html
{% extends 'base/base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% load tailwind_filters %}

{% block title %}Users{% endblock title %}

{% block body %}
<div class="flex items-center justify-center mt-4 mb-2">
    {% if users %}
        {% for user in users %}
        <div class="mx-2 my-2 px-6 py-6 flex flex-col items-center shadow-md">
            <img class="w-32 h-32 rounded-full" src="{{ user.avatar.url }}" alt="profile picture">
            <h5 class="mt-2">{{ user.email }}</h5>
            <h5 class="mt-2">{{ user.name }}</h5>
            <a class="mt-2 px-3 py-2 bg-blue-500 hover:bg-blue-700 rounded" href="{% url 'base:profile' user_id=user.id %}">Show</a>
        </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock body %}